---

- name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
  apt:
    name: nginx
    state: latest
    update_cache: yes

# - hosts: all
#   become: yes
#   tasks:

#     - name: update
#       apt: update_cache=yes

#     - name: Install Nginx
#       apt: name=nginx state=latest

#       notify:
#         - restart nginx

#   handlers:
#     - name: restart nginx
#       service: name=nginx state=reloaded

# - hosts: all
#   become: true
#   tasks:
#     - name: Install Nginx
#       apt:
#         name: nginx
#         state: present

- name: Enable default Nginx website
  file:
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
    state: link

- name: Set landing page
  template:
    src=index.html.j2
    dest=/var/www/html/index.nginx-debian.html
    backup=yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
